---
version: '3.6'

services:
  traefik:
    image: traefik
    command: --docker.swarmmode --docker.domain=gaia.local --docker.watch -l DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik_network"

  # Torrent downloader (https://transmissionbt.com/)
  transmission:
    image: linuxserver/transmission
    volumes:
      - /opt/appdata/transmission/config:/config
      - /mnt/storage/Downloads/Torrents:/downloads
      - /mnt/storage/Videos/Movies:/movies
      - /mnt/storage/Downloads/Torrents/.incomplete:/downloads/.incomplete
      - /mnt/storage/Downloads/Torrents/.watch:/watch
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Paris
    ports:
      - "51413:51413"
      - "51413:51413/udp"
      - "9091:9091"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.port=9091"

  # Home media server (https://emby.media/)
  emby:
    image: emby/embyserver
    volumes:
      - /opt/appdata/emby/config:/config
      - /mnt/storage/Videos/Movies:/mnt/movies
      - /mnt/storage/Videos/TVShows:/mnt/tvshows
      - /mnt/storage/Videos/TV:/mnt/tv
      - /mnt/storage/Videos/Animation Movies:/mnt/animation
      - /mnt/storage/Videos/Anime:/mnt/animes
      - /mnt/storage/Audio/Music:/mnt/music
      - /mnt/storage/Books/Books:/mnt/books
      - /mnt/storage/Images/Photos:/mnt/photos
      - /mnt/storage/Downloads/Torrents:/mnt/downloads
    environment:
      - UID=${PUID}
      - GID=${PGID}
        #    networks:
        #      - traefik_network 
    ports:
      - "8096:8096"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.port=8096"
        - "traefik.frontend.rule=PathPrefix:/,/emby"

  # Open, trustworthy and decentralized sync and cloud services (https://syncthing.net/)
  syncthing:
    image: linuxserver/syncthing
    volumes:
      - /opt/appdata/syncthing/config:/config
      - /mnt/storage/Audio/Sync:/singles
      - /mnt/storage/Books:/books
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Paris
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.port=8384"
          #- "traefik.frontend.rule=Path:/sync"
        - "traefik.frontend.rule=PathPrefixStrip: /syncthing/"

networks:
  default:
      name: traefik_network
