---
version: '3.6'

services:
  traefik:
    image: traefik 
    command: --docker.swarmmode --docker.domain=traefik --docker.watch # --docker.endpoint=unix://var/run/docker.sock -l DEBUG
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - "traefik_network"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=gaia_traefik_network"

  # Home media server (https://emby.media/)
  emby:
    image: emby/embyserver
    volumes:
      - /opt/appdata/emby/config:/config
      - /mnt/storage/videos/movies:/mnt/movies
      - /mnt/storage/videos/tvshow:/mnt/tvshows
      - /mnt/storage/audio/music:/mnt/music
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - TZ=Europe/Paris
    networks:
        - traefik_network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.frontend.rule=PathPrefix:/emby"
        - "traefik.port=8096"

# Browsing, reading and downloading eBooks (https://github.com/janeczku/calibre-web)
#  freshrss:
#    image: linuxserver/freshrss
#    container_name: freshrss
#    restart: always
#    volumes:
#      - /opt/appdata/freshrss/config:/config
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=Europe/Paris
#    labels:
#      - "traefik.enable=true"
#      - "traefik.port=80"
#      - "traefik.frontend.rule=Host:feeds.localhost"

#  koel:
#    image: 0xcaff/koel
#    container_name: koel
#    depends_on:
#      - database
#    ports:
#      - 80:80
#    environment:
#      DB_CONNECTION: mysql
#      DB_HOST: database
#      DB_USERNAME: koel
#      DB_PASSWORD: koel
#      DB_DATABASE: koel
#    volumes:
#      - /mnt/storage/audio/music:/music
#    labels:
#      - "traefik.enable=true"
#      - "traefik.port=80"
#      - "traefik.frontend.rule=Host:music.localhost"
#
#  database:
#    image: mysql/mysql-server:5.7
#    container_name: mysql
#    volumes:
#      - /opt/appdata/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: MonSuperMDPMySQL1933!
#      MYSQL_DATABASE: koel
#      MYSQL_USER: koel
#      MYSQL_PASSWORD: koel

## wiki app (https://wiki.js.org/)
#  wikidb:
#    image: mongo
#    container_name: wikijs_db
#    expose:
#      - '27017'
#    command: '--smallfiles --bind_ip wikidb'
#    environment:
#      - 'MONGO_LOG_DIR=/dev/null'
#    volumes:
#      - /opt/appdata/mongo:/data/db
#  wikijs:
#    image: 'requarks/wiki:latest'
#    container_name: wikijs
#    links:
#      - wikidb
#    depends_on:
#      - wikidb
#    environment:
#      WIKI_ADMIN_EMAIL: support@dizolo.eu
#    volumes:
#      - /opt/appdata/wikijs/config.yml:/var/wiki/config.yml
#    labels:
#      - "traefik.enable=true"
#      - "traefik.port=3000"
#      - "traefik.frontend.rule=Host:wiki.localhost"

#  # Browsing, reading and downloading eBooks (https://github.com/janeczku/calibre-web)
#  calibre-web:
#    image: linuxserver/calibre-web
#    container_name: calibre
#    restart: always
#    volumes:
#      - /opt/appdata/calibre-web/config:/config
#      - /home/br3wal/Livres:/books
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=Europe/Paris
#    labels:
#      - "traefik.enable=true"
#      - "traefik.port=8083"
#      - "traefik.frontend.rule=Host:calibre.localhost"
networks:
  traefik_network:
    driver: overlay
