debug = true

logLevel = "ERROR" ## DEBUG, INFO, WARN, ERROR, FATAL, PANIC
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "dizolo.eu"
watch = true
exposedByDefault = false

[acme]
email = "postmaster@dizolo.eu"
storage = "assets/acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
